from jobs.specs.dev_i3d_smth import dev_i3d_smth
from jobs.specs.dev_lrcn_smth import dev_lrcn_smth
from jobs.specs.dev_tadn_smth import dev_tadn_smth
from jobs.specs.dev_vaei3d_smth_ce import dev_vaei3d_smth_ce
from jobs.specs.dev_vaei3d_smth_ce_kld import dev_vaei3d_smth_ce_kld
from jobs.specs.dev_vaei3d_smth_ce_kld_mse import dev_vaei3d_smth_ce_kld_mse
from jobs.specs.dev_vaei3d_smth_mse import dev_vaei3d_smth_mse
from jobs.specs.dev_vaei3d_smth_mse_kld import dev_vaei3d_smth_mse_kld
from jobs.specs.i3d_smth_025 import i3d_smth_025
from jobs.specs.i3d_smth_025_resume import i3d_smth_025_resume
from jobs.specs.i3d_smth_050 import i3d_smth_050
from jobs.specs.i3d_smth_050_resume import i3d_smth_050_resume
from jobs.specs.i3d_smth_075 import i3d_smth_075
from jobs.specs.i3d_smth_075_resume import i3d_smth_075_resume
from jobs.specs.i3d_smth_100 import i3d_smth_100
from jobs.specs.i3d_smth_100_resume import i3d_smth_100_resume
from jobs.specs.lrcn_smth_025 import lrcn_smth_025
from jobs.specs.lrcn_smth_025_resume import lrcn_smth_025_resume
from jobs.specs.lrcn_smth_050 import lrcn_smth_050
from jobs.specs.lrcn_smth_050_resume import lrcn_smth_050_resume
from jobs.specs.lrcn_smth_100 import lrcn_smth_100
from jobs.specs.lrcn_smth_100_resume import lrcn_smth_100_resume
from jobs.specs.tadn_smth_025 import tadn_smth_025
from jobs.specs.tadn_smth_025_resume import tadn_smth_025_resume
from jobs.specs.tadn_smth_050 import tadn_smth_050
from jobs.specs.tadn_smth_050_resume import tadn_smth_050_resume
from jobs.specs.tadn_smth_075 import tadn_smth_075
from jobs.specs.tadn_smth_075_resume import tadn_smth_075_resume
from jobs.specs.tadn_smth_100 import tadn_smth_100
from jobs.specs.tadn_smth_100_resume import tadn_smth_100_resume
from jobs.specs.vaei3d_smth_100 import vaei3d_smth_100
from jobs.specs.vaei3d_smth_100_resume import vaei3d_smth_100_resume
